<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Concat\DirnameDirConcatStringToDirectStringPathRector;
use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/config',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ])
    ->withSkip([
        // Regenerated by Symfony/Flex, never edited by hand
        __DIR__.'/config/bundles.php',
        __DIR__.'/config/reference.php',
        // Keep Symfony's dirname(__DIR__) convention used by all recipes
        DirnameDirConcatStringToDirectStringPathRector::class,
    ])
    // PHP version is read from composer.json ("php": ">=8.5.11")
    ->withPhpSets()
    ->withAttributesSets()
    // Upgrade sets are picked from the installed package versions
    ->withComposerBased(twig: true, doctrine: true, phpunit: true, symfony: true)
    ->withSymfonyContainerXml(__DIR__.'/var/cache/dev/App_KernelDevDebugContainer.xml')
    ->withPreparedSets(
        deadCode: true,
        codeQuality: true,
        typeDeclarations: true,
    )
    ->withImportNames(importShortClasses: false)
    // Inside the project, so it does not depend on who created /tmp/rector_cached_files
    ->withCache(
        cacheDirectory: __DIR__.'/var/cache/rector',
        containerCacheDirectory: __DIR__.'/var/cache/rector',
    )
;
